[workspace]
resolver = "3"
members = [
    "proj_031_variables",
    "proj_032_data_types",
    "proj_033_functions",
    "proj_034_comments", "proj_035_control_flow", "proj_041_what_is_ownership",
]
